[tool.ruff]
line-length = 110
output-format = "grouped"
target-version = "py37"

[tool.ruff.lint]
select = [
    "A",  # flake8-builtins
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "E",  # pycodestyle - errors
    "EXE",  # flake8-executable
    "F",  # pyflakes
    "FA",  # flake8-future-annotations
    "FLY",  # flynt
    "I",  # isort
    "ICN",  # flake8-import-conventions
    "ISC",  # flake8-implicit-str-concat
    "LOG",  # flake8-logging
    "N",  # pep8-naming
    "NPY",  # numpy-specific rules
    "PD",  # pandas-vet
    "PERF",  # perflint
    "PIE",  # flake8-pie
    "PGH",  # pygrep-hooks
    "PLC",  # pylint-convention
    "PLE",  # pylint-error
    "PYI024",  # flake8-pyi
    "Q",  # flake8-quotes
    "RSE",  # flake8-raise
    "RUF",  # ruff specific rules
    "SLOT",  # flake8-slots
    "T10",  # flake8-debugger
    "TCH",  # flake8-type-checking
    "TID",  # flake8-tidy-imports
    "W",  # pycodestyle - warnings
    "YTT",  # flake8-2020
]

[tool.pytest.ini_options]
testpaths = ["configurable_http_proxy_test"]

[tool.coverage.run]
branch = true
cover_pylib = false
source = ["."]
include = ["configurable_http_proxy/*"]

[tool.coverage.report]
show_missing = true
skip_covered = false
sort = "Miss"
include = ["configurable_http_proxy/*"]
